
package cl.group.dispacher.ws.tarifacion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExternoTarificacion", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://b2b.correos.cl/ServicioTarificacionCEPEmpresasExterno/cch/ws/tarificacionCEP/externo/implementacion/ExternoTarificacion.asmx?WSDL")
public class ExternoTarificacion
    extends Service
{

    private final static URL EXTERNOTARIFICACION_WSDL_LOCATION;
    private final static WebServiceException EXTERNOTARIFICACION_EXCEPTION;
    private final static QName EXTERNOTARIFICACION_QNAME = new QName("http://tempuri.org/", "ExternoTarificacion");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("file:/C:/Users/David/AppData/Local/Temp/tempdir17908932715683098079.tmp/ExternoTarificacion_1.wsdl");
            url = new URL("http://b2b.correos.cl/ServicioTarificacionCEPEmpresasExterno/cch/ws/tarificacionCEP/externo/implementacion/ExternoTarificacion.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXTERNOTARIFICACION_WSDL_LOCATION = url;
        EXTERNOTARIFICACION_EXCEPTION = e;
    }

    public ExternoTarificacion() {
        super(__getWsdlLocation(), EXTERNOTARIFICACION_QNAME);
    }

    public ExternoTarificacion(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXTERNOTARIFICACION_QNAME, features);
    }

    public ExternoTarificacion(URL wsdlLocation) {
        super(wsdlLocation, EXTERNOTARIFICACION_QNAME);
    }

    public ExternoTarificacion(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXTERNOTARIFICACION_QNAME, features);
    }

    public ExternoTarificacion(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExternoTarificacion(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExternoTarificacionSoap
     */
    @WebEndpoint(name = "ExternoTarificacionSoap")
    public ExternoTarificacionSoap getExternoTarificacionSoap() {
        return super.getPort(new QName("http://tempuri.org/", "ExternoTarificacionSoap"), ExternoTarificacionSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExternoTarificacionSoap
     */
    @WebEndpoint(name = "ExternoTarificacionSoap")
    public ExternoTarificacionSoap getExternoTarificacionSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ExternoTarificacionSoap"), ExternoTarificacionSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXTERNOTARIFICACION_EXCEPTION!= null) {
            throw EXTERNOTARIFICACION_EXCEPTION;
        }
        return EXTERNOTARIFICACION_WSDL_LOCATION;
    }

}
