
package cl.group.dispacher.ws.tarifacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExternoTarificacionSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExternoTarificacionSoap {


    /**
     * Servicio web consulta productos por cliente.
     * 
     * @param usuario
     * @param contrasena
     * @return
     *     returns cl.group.dispacher.ws.tarifacion.ArrayOfProductoTO
     */
    @WebMethod(action = "http://tempuri.org/consultaProductosPorCliente")
    @WebResult(name = "consultaProductosPorClienteResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "consultaProductosPorCliente", targetNamespace = "http://tempuri.org/", className = "cl.group.dispacher.ws.tarifacion.ConsultaProductosPorCliente")
    @ResponseWrapper(localName = "consultaProductosPorClienteResponse", targetNamespace = "http://tempuri.org/", className = "cl.group.dispacher.ws.tarifacion.ConsultaProductosPorClienteResponse")
    public ArrayOfProductoTO consultaProductosPorCliente(
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "contrasena", targetNamespace = "http://tempuri.org/")
        String contrasena);

    /**
     * Metodo web que permite obtener servicios de acuerdo a una cobertura.
     * 
     * @param consultaCobertura
     * @param usuario
     * @param contrasena
     * @return
     *     returns cl.group.dispacher.ws.tarifacion.ArrayOfServicioTO
     */
    @WebMethod(action = "http://tempuri.org/consultaCobertura")
    @WebResult(name = "consultaCoberturaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "consultaCobertura", targetNamespace = "http://tempuri.org/", className = "cl.group.dispacher.ws.tarifacion.ConsultaCobertura")
    @ResponseWrapper(localName = "consultaCoberturaResponse", targetNamespace = "http://tempuri.org/", className = "cl.group.dispacher.ws.tarifacion.ConsultaCoberturaResponse")
    public ArrayOfServicioTO consultaCobertura(
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "contrasena", targetNamespace = "http://tempuri.org/")
        String contrasena,
        @WebParam(name = "consultaCobertura", targetNamespace = "http://tempuri.org/")
        CoberturaTO consultaCobertura);

    /**
     * Metodo web que permite obtener servicio de acuerdo a una cobertura.
     * 
     * @param consultaCobertura
     * @param usuario
     * @param contrasena
     * @return
     *     returns cl.group.dispacher.ws.tarifacion.ServicioTO
     */
    @WebMethod(action = "http://tempuri.org/consultaCoberturaPorProducto")
    @WebResult(name = "consultaCoberturaPorProductoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "consultaCoberturaPorProducto", targetNamespace = "http://tempuri.org/", className = "cl.group.dispacher.ws.tarifacion.ConsultaCoberturaPorProducto")
    @ResponseWrapper(localName = "consultaCoberturaPorProductoResponse", targetNamespace = "http://tempuri.org/", className = "cl.group.dispacher.ws.tarifacion.ConsultaCoberturaPorProductoResponse")
    public ServicioTO consultaCoberturaPorProducto(
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "contrasena", targetNamespace = "http://tempuri.org/")
        String contrasena,
        @WebParam(name = "consultaCobertura", targetNamespace = "http://tempuri.org/")
        CoberturaProductoTO consultaCobertura);

}
