
package cl.group.dispacher.ws.admision;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioExternoAdmisionCEPSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioExternoAdmisionCEPSoap {


    /**
     * Método web que permite realizar una admisión CEP.
     * 
     * @param admisionTo
     * @param usuario
     * @param contrasena
     * @return
     *     returns cl.group.dispacher.ws.admision.RespuestaAdmisionTO
     */
    @WebMethod(action = "http://tempuri.org/admitirEnvio")
    @WebResult(name = "admitirEnvioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "admitirEnvio", targetNamespace = "http://tempuri.org/", className = "cl.group.dispacher.ws.admision.AdmitirEnvio")
    @ResponseWrapper(localName = "admitirEnvioResponse", targetNamespace = "http://tempuri.org/", className = "cl.group.dispacher.ws.admision.AdmitirEnvioResponse")
    public RespuestaAdmisionTO admitirEnvio(
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "contrasena", targetNamespace = "http://tempuri.org/")
        String contrasena,
        @WebParam(name = "admisionTo", targetNamespace = "http://tempuri.org/")
        AdmisionTO admisionTo);

}
