
package cl.group.dispacher.ws.admision;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioExternoAdmisionCEP", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://b2b.correos.cl/ServicioAdmisionCEPExterno/cch/ws/enviosCEP/externo/implementacion/ServicioExternoAdmisionCEP.asmx?WSDL")
public class ServicioExternoAdmisionCEP
    extends Service
{

    private final static URL SERVICIOEXTERNOADMISIONCEP_WSDL_LOCATION;
    private final static WebServiceException SERVICIOEXTERNOADMISIONCEP_EXCEPTION;
    private final static QName SERVICIOEXTERNOADMISIONCEP_QNAME = new QName("http://tempuri.org/", "ServicioExternoAdmisionCEP");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://b2b.correos.cl/ServicioAdmisionCEPExterno/cch/ws/enviosCEP/externo/implementacion/ServicioExternoAdmisionCEP.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOEXTERNOADMISIONCEP_WSDL_LOCATION = url;
        SERVICIOEXTERNOADMISIONCEP_EXCEPTION = e;
    }

    public ServicioExternoAdmisionCEP() {
        super(__getWsdlLocation(), SERVICIOEXTERNOADMISIONCEP_QNAME);
    }

    public ServicioExternoAdmisionCEP(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOEXTERNOADMISIONCEP_QNAME, features);
    }

    public ServicioExternoAdmisionCEP(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOEXTERNOADMISIONCEP_QNAME);
    }

    public ServicioExternoAdmisionCEP(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOEXTERNOADMISIONCEP_QNAME, features);
    }

    public ServicioExternoAdmisionCEP(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioExternoAdmisionCEP(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioExternoAdmisionCEPSoap
     */
    @WebEndpoint(name = "ServicioExternoAdmisionCEPSoap")
    public ServicioExternoAdmisionCEPSoap getServicioExternoAdmisionCEPSoap() {
        return super.getPort(new QName("http://tempuri.org/", "ServicioExternoAdmisionCEPSoap"), ServicioExternoAdmisionCEPSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioExternoAdmisionCEPSoap
     */
    @WebEndpoint(name = "ServicioExternoAdmisionCEPSoap")
    public ServicioExternoAdmisionCEPSoap getServicioExternoAdmisionCEPSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ServicioExternoAdmisionCEPSoap"), ServicioExternoAdmisionCEPSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOEXTERNOADMISIONCEP_EXCEPTION!= null) {
            throw SERVICIOEXTERNOADMISIONCEP_EXCEPTION;
        }
        return SERVICIOEXTERNOADMISIONCEP_WSDL_LOCATION;
    }

}
