
package cl.group.dispacher.ws.normalizacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioExternoNormalizacionSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioExternoNormalizacionSoap {


    /**
     * Método que normaliza una dirección.
     * 
     * @param direccion
     * @param comuna
     * @param usuario
     * @param contrasena
     * @param id
     * @return
     *     returns cl.group.dispacher.ws.normalizacion.DireccionNormalizadaTO
     */
    @WebMethod(action = "http://tempuri.org/normalizarDireccion")
    @WebResult(name = "normalizarDireccionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "normalizarDireccion", targetNamespace = "http://tempuri.org/", className = "cl.group.dispacher.ws.normalizacion.NormalizarDireccion")
    @ResponseWrapper(localName = "normalizarDireccionResponse", targetNamespace = "http://tempuri.org/", className = "cl.group.dispacher.ws.normalizacion.NormalizarDireccionResponse")
    public DireccionNormalizadaTO normalizarDireccion(
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "contrasena", targetNamespace = "http://tempuri.org/")
        String contrasena,
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        String id,
        @WebParam(name = "direccion", targetNamespace = "http://tempuri.org/")
        String direccion,
        @WebParam(name = "comuna", targetNamespace = "http://tempuri.org/")
        String comuna);

}
