
package cl.group.dispacher.ws.regionComuna;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioExternoRegionYComunasSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioExternoRegionYComunasSoap {


    /**
     * M�todo web que permite obtener un listado de todas las regiones almacenadas en el repositorio de datos.
     * 
     * @param usuario
     * @param contrasena
     * @return
     *     returns cl.group.dispacher.ArrayOfRegionTO
     */
    @WebMethod(action = "http://tempuri.org/listarTodasLasRegiones")
    @WebResult(name = "listarTodasLasRegionesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "listarTodasLasRegiones", targetNamespace = "http://tempuri.org/", className = "cl.group.dispacher.ListarTodasLasRegiones")
    @ResponseWrapper(localName = "listarTodasLasRegionesResponse", targetNamespace = "http://tempuri.org/", className = "cl.group.dispacher.ListarTodasLasRegionesResponse")
    public ArrayOfRegionTO listarTodasLasRegiones(
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "contrasena", targetNamespace = "http://tempuri.org/")
        String contrasena);

    /**
     * M�todo que permite obtener un listado con todas las comunas almacenadas en el repositorio de datos, seg�n la regi�n indicada por su identificador.
     * 
     * @param usuario
     * @param contrasena
     * @param codigoRegion
     * @return
     *     returns cl.group.dispacher.ArrayOfComunaTO
     */
    @WebMethod(action = "http://tempuri.org/listarComunasSegunRegion")
    @WebResult(name = "listarComunasSegunRegionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "listarComunasSegunRegion", targetNamespace = "http://tempuri.org/", className = "cl.group.dispacher.ListarComunasSegunRegion")
    @ResponseWrapper(localName = "listarComunasSegunRegionResponse", targetNamespace = "http://tempuri.org/", className = "cl.group.dispacher.ListarComunasSegunRegionResponse")
    public ArrayOfComunaTO listarComunasSegunRegion(
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "contrasena", targetNamespace = "http://tempuri.org/")
        String contrasena,
        @WebParam(name = "codigoRegion", targetNamespace = "http://tempuri.org/")
        String codigoRegion);

    /**
     * M�todo web que permite obtener un listado de todas las comunas almacenadas en en el repositorio de datos.
     * 
     * @param usuario
     * @param contrasena
     * @return
     *     returns cl.group.dispacher.ArrayOfComunaTO
     */
    @WebMethod(action = "http://tempuri.org/listarTodasLasComunas")
    @WebResult(name = "listarTodasLasComunasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "listarTodasLasComunas", targetNamespace = "http://tempuri.org/", className = "cl.group.dispacher.ListarTodasLasComunas")
    @ResponseWrapper(localName = "listarTodasLasComunasResponse", targetNamespace = "http://tempuri.org/", className = "cl.group.dispacher.ListarTodasLasComunasResponse")
    public ArrayOfComunaTO listarTodasLasComunas(
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "contrasena", targetNamespace = "http://tempuri.org/")
        String contrasena);

}
