
package cl.group.dispacher.ws.regionComuna;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioExternoRegionYComunas", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://apicert.correos.cl:8008/ServicioRegionYComunasExterno/cch/ws/distribucionGeografica/externo/implementacion/ServicioExternoRegionYComunas.asmx?WSDL")
public class ServicioExternoRegionYComunas
    extends Service
{

    private final static URL SERVICIOEXTERNOREGIONYCOMUNAS_WSDL_LOCATION;
    private final static WebServiceException SERVICIOEXTERNOREGIONYCOMUNAS_EXCEPTION;
    private final static QName SERVICIOEXTERNOREGIONYCOMUNAS_QNAME = new QName("http://tempuri.org/", "ServicioExternoRegionYComunas");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://apicert.correos.cl:8008/ServicioRegionYComunasExterno/cch/ws/distribucionGeografica/externo/implementacion/ServicioExternoRegionYComunas.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOEXTERNOREGIONYCOMUNAS_WSDL_LOCATION = url;
        SERVICIOEXTERNOREGIONYCOMUNAS_EXCEPTION = e;
    }

    public ServicioExternoRegionYComunas() {
        super(__getWsdlLocation(), SERVICIOEXTERNOREGIONYCOMUNAS_QNAME);
    }

    public ServicioExternoRegionYComunas(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOEXTERNOREGIONYCOMUNAS_QNAME, features);
    }

    public ServicioExternoRegionYComunas(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOEXTERNOREGIONYCOMUNAS_QNAME);
    }

    public ServicioExternoRegionYComunas(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOEXTERNOREGIONYCOMUNAS_QNAME, features);
    }

    public ServicioExternoRegionYComunas(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioExternoRegionYComunas(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioExternoRegionYComunasSoap
     */
    @WebEndpoint(name = "ServicioExternoRegionYComunasSoap")
    public ServicioExternoRegionYComunasSoap getServicioExternoRegionYComunasSoap() {
        return super.getPort(new QName("http://tempuri.org/", "ServicioExternoRegionYComunasSoap"), ServicioExternoRegionYComunasSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioExternoRegionYComunasSoap
     */
    @WebEndpoint(name = "ServicioExternoRegionYComunasSoap")
    public ServicioExternoRegionYComunasSoap getServicioExternoRegionYComunasSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ServicioExternoRegionYComunasSoap"), ServicioExternoRegionYComunasSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOEXTERNOREGIONYCOMUNAS_EXCEPTION!= null) {
            throw SERVICIOEXTERNOREGIONYCOMUNAS_EXCEPTION;
        }
        return SERVICIOEXTERNOREGIONYCOMUNAS_WSDL_LOCATION;
    }

}
